### ISSUE TITLE
ValueError: expected 2D or 3D input (got 1D input)

### ISSUE THREAD

**Issue by WhiteXiezx** [daizuozhuo/batch-feature-erasing-network#1]
hi~，thank you for sharing your job.  when I run main_reid.py for evaluating pre-trained models on market1501 datasets, I meet a problem of ValueError: expected 2D or 3D input (got 1D input), line 68, in evaluate,  feature0 = self._forward(inputs)

**Comment by daizuozhuo** [comment]
Could you share your running commands and the number of GPUs used? This error is often caused by the incorrect batch size setting.

**Comment by WhiteXiezx** [comment]
python3 main_reid.py train --save_dir='./pytorch-ckpt/market_label_bfe' --model_name=bfe --train_batch=32 --test_batch=32 --dataset=market1501 --pretrained_model='./pytorch-ckpt/market_label_bfe/market_944.pth.tar' --evaluate

{'adjust_lr': False,
 'best_rank': -inf,
 'dataset': 'market1501',
 'datatype': 'person',
 'eval_step': 50,
 'evaluate': True,
 'gamma': 0.1,
 'last_stride': 1,
 'loss': 'triplet',
 'lr': 0.0001,
 'margin': None,
 'max_epoch': 60,
 'mode': 'retrieval',
 'model_name': 'bfe',
 'momentum': 0.9,
 'num_gpu': 1,
 'num_instances': 4,
 'optim': 'adam',
 'pretrained_model': './pytorch-ckpt/market_label_bfe/market_944.pth.tar',
 'print_freq': 30,
 'random_crop': False,
 're_ranking': False,
 'save_dir': './pytorch-ckpt/market_label_bfe',
 'savefig': None,
 'seed': 0,
 'start_epoch': 0,
 'test_batch': 32,
 'train_batch': 32,
 'weight_decay': 0.0005,
 'workers': 10}

**Comment by WangweiDamon** [comment]
@Maybe you should change "--dataset" to your own Market1501 dataset folder(path). 

=========user config==========
{'adjust_lr': False,
 'best_rank': -inf,
 'dataset': 'Market-1501-v15.09.15',
 'datatype': 'person',
 'eval_step': 50,
 'evaluate': True,
 'gamma': 0.1,
 'last_stride': 1,
 'loss': 'triplet',
 'lr': 0.0001,
 'margin': None,
 'max_epoch': 60,
 'mode': 'retrieval',
 'model_name': 'bfe',
 'momentum': 0.9,
 'num_gpu': 3,
 'num_instances': 4,
 'optim': 'adam',
 'pretrained_model': './pretrained_models/Market1501/market_944.pth.tar',
 'print_freq': 30,
 'random_crop': False,
 're_ranking': False,
 'save_dir': './pytorch-ckpt/market_bfe',
 'savefig': None,
 'seed': 0,
 'start_epoch': 0,
 'test_batch': 32,
 'train_batch': 32,
 'weight_decay': 0.0005,
 'workers': 8}

**Comment by WhiteXiezx** [comment]
@daizuozhuo @WangweiDamon thank you for your kind reply, I have solved this problem by setting test_batch and train_batch 31 and finally got the results, I'm new to pytorch and try to find the reason for this error.
