### ISSUE TITLE
reproduce for image retrieval for deep fashion in-shop retrieval task

### ISSUE THREAD

**Issue by bloatybo** [daizuozhuo/batch-feature-erasing-network#3]
![image](https://user-images.githubusercontent.com/10253181/51356406-4acaaf80-1a6f-11e9-9477-144923154075.png)
as in your paper "Batch Feature Erasing for Person Re-identification and Beyond"
I wonder if you can provide the code to reproduce the results of deep fashion in-shop retrieval task? or some trianed model?
Thanks!

**Comment by daizuozhuo** [comment]
@bloatybo Hi, the dataset and model are released. Please have a look at the updated README.md.
