### ISSUE TITLE
a question about code

### ISSUE THREAD

**Issue by gk-cv** [daizuozhuo/batch-feature-erasing-network#4]
hi, thank you for release your code. two lines below has different order of w_ratio and h_ratio in your code.

self.batch_crop = BatchDrop(width_ratio, height_ratio)

def __init__(self, h_ratio, w_ratio):

should change its order or not?

**Comment by daizuozhuo** [comment]
@gk-cv Yes, you are right. I've fixed the order. Thank you very much.
