### ISSUE TITLE
About re_ranking

### ISSUE THREAD

**Issue by YuPeize** [daizuozhuo/batch-feature-erasing-network#7]
It seems that it is no use to set the parameter `--re_ranking = True` if I want to use re-ranking, because the following code in Line 171 in `main_reid.py`
`rank1 = reid_evaluator.evaluate(queryloader, galleryloader, queryFliploader, galleryFliploader)`
doesn't pass the parameter `opt.re_ranking`.

**Comment by daizuozhuo** [comment]
the re_ranking function is not tested so we do not use it now.
