### ISSUE TITLE
with provided market_953.pth.tar, unable to get 95.3 rank1 results 

### ISSUE THREAD

**Issue by sijun-zhou** [daizuozhuo/batch-feature-erasing-network#8]
Hi,
Thanks a lot for your provided codes and models. 

But with your provided with provided model **“market_953.pth.tar”**, and your code main_reid.py, I cannot get the result of rank1 95.3%.
Is there any tricks to play with inference? Thanks in advance!

I run the following command:
python3 main_reid.py train --save_dir='./pytorch-ckpt/market_bfe' --model_name=bfe --train_batch=32 --test_batch=32 --dataset=market1501 --pretrained_model='./pytorch-ckpt/market_bfe/market_953.pth.tar' --evaluate

And I get the market1501 dataset from the below link:
https://jingdongwang2017.github.io/Projects/ReID/Datasets/Market-1501.html

resuls:
=> Market1501 loaded
Dataset statistics:
  ------------------------------
  subset   | # ids | # images
  ------------------------------
  train    |   751 |    12936
  query    |   750 |     3368
  gallery  |   751 |    15913
  ------------------------------
  total    |  1501 |    32217
  ------------------------------
initializing model ...
load pretrained model ./pytorch-ckpt/market_bfe/market_953.pth.tar
model size: 32.27600M
Extracted features for query set: 3368 x 1536
Extracted features for gallery set: 15913 x 1536
Computing distance matrix
Computing CMC and mAP
Results ----------
mAP: 85.5%
CMC curve
Rank-1  : 94.6%
Rank-2  : 96.5%
Rank-4  : 97.4%
Rank-5  : 97.8%
Rank-8  : 98.4%
Rank-10 : 98.8%
Rank-16 : 99.3%
Rank-20 : 99.3%
------------------

hardwares and softwares:
GPU : 2080TI     CUDA:10.0     pytorch:1.0.0

**Comment by TomHeaven** [comment]
I meet the same problem. Did you solve it? @sijun-zhou
